sudo: required
dist: trusty
language: cpp
env:
  - BIG_INT="-DVAR_INT_SUPPORT=0"
  - BIG_INT="-DVAR_INT_SUPPORT=1"
compiler:
  - gcc
  - clang
before_install:
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo apt-get install -y libboost-all-dev libboost-test-dev lcov; fi
  - if [ $TRAVIS_OS_NAME == linux ]; then sudo pip install -U cpp-coveralls; fi
script:
  - if [ $TRAVIS_OS_NAME == linux ]; then cd runtime && cmake $BIG_INT -DCMAKE_BUILD_TYPE=Debug -DDO_COVERAGE=1 -DBUILD_UNIT_TESTS=1 . && make VERBOSE=1 && ./tests/TestBER; fi
  - if [ $TRAVIS_OS_NAME == osx ]; then cd runtime && cmake $BIG_INT -DCMAKE_BUILD_TYPE=Debug -DBUILD_UNIT_TESTS=1 . && make VERBOSE=1 && ./tests/TestBER; fi
after_success:
  - if [ $TRAVIS_OS_NAME == linux ]; then coveralls --gcov-options '\-lp'; fi
os:
  - linux
  - osx
